flutter_analyze_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  pub_get_script: flutter pub get
  lint_script: flutter analyze

flutter_drive_ios_task:
  osx_instance:
    image: catalina-flutter
  open_simulator_script: open -a Simulator
  test_script: make test

flutter_drive_android_task:
  container:
    image: cirrusci/flutter:stable
    kvm: true
    cpu: 4
    memory: 16G
  env:
    EMULATOR_API_LEVEL: 29
    ANDROID_ABI: "default;x86"
  fix_kvm_script: sudo chown cirrus:cirrus /dev/kvm
  update_emulator_script: sdkmanager --verbose --channel=0 "emulator"
  update_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script: echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script: $ANDROID_HOME/emulator/emulator -verbose -avd test -no-audio -no-window
  wait_for_emulator_script:
    - ./scripts/android-wait-for-emulator.sh
  pub_cache:
    folder: ~/.pub-cache
  android_cache:
    folder: ~/.android/build-cache/
  test_script: make test
