name: native_webview
description: A Flutter plugin that allows you to add an inline WebView.
version: 0.0.1
homepage: https://github.com/hisaichi5518/native_webview

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jp.packages.native_webview
        pluginClass: NativeWebviewPlugin
      ios:
        pluginClass: NativeWebviewPlugin
